# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

proxy_app = "tcp://127.0.0.1:44001"
fast_sync = true
db_backend = "leveldb"
log_level = "debug"

[rpc]
laddr = "tcp://0.0.0.0:42001"

[p2p]
laddr = "tcp://0.0.0.0:40001"
seeds = "0.0.0.0:40000,0.0.0.0:40001,0.0.0.0:40002,0.0.0.0:40003"
